### ISSUE TITLE
Error deserializing with NULL Geometry

### ISSUE THREAD

**Issue by blackboxlogic** [bamcis-io/GeoJSON#11]
With: `var data = JsonConvert.DeserializeObject<GeoJson>(json);`
I get:
'Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'features[0].geometry', line 12, position 28.'

from this file:
```
{
    "type": "FeatureCollection",
    "crs": {
        "type": "name",
        "properties": {
            "name": "EPSG:4326"
        }
    },
    "features": [{
            "type": "Feature",
            "id": 1484657,
            "geometry": null,
            "properties": {
...
```

This file is an export from GIS. I can't tell if the file doesn't meet the GeoJson standard or if the library can't handle a valid case.

**Comment by blackboxlogic** [comment]
My issue was resolved by adding `returnGeometry=true` to the GIS query, which included valid data in the `geometry` field.

**Comment by hakenmt** [comment]
I'm actually going to reopen this (thank you for bringing it to my attention). The RFC for GeoJson does allow for geometry and properties to be null.

   o  A Feature object has a member with the name "geometry".  The value
      of the geometry member SHALL be either a Geometry object as
      defined above or, in the case that the Feature is unlocated, a
      JSON null value.

   o  A Feature object has a member with the name "properties".  The
      value of the properties member is an object (any JSON object or a
      JSON null value).

This is a bug that will be fixed.

**Comment by blackboxlogic** [comment]
Thanks for fixing this!
