### ISSUE TITLE
Null value parsing

### ISSUE THREAD

**Issue by ignasbagdonas** [bamcis-io/GeoJSON#13]
Hey, I have tried library, it's awesome, but I have an issue with null value.

I have created my Dto object which has several GeoJson properties:
```
public class ParkingZoneDto
 {
        [JsonProperty]
        public int Id { get; set; }

        [JsonProperty]
        public string Name { get; set; }

        [JsonProperty]
        public GeoJson GeographyPolygons { get; set; }

        [JsonProperty]
        public GeoJson PinPositions { get; set; }
}
```

And JsonConvert.DeserializeObject failing when in the response property PinPossitions is null (some times here should be MultiPoint) :
```
{
    ...,
    "PinPositions": null,
    ...
}
```

Error is: `Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path '[0].PinPositions', line 1, position 41.
  at Newtonsoft.Json.Linq.JObject.Load (Newtonsoft.Json.JsonReader reader,...`

If I removed that property from my response string, then deserialization success and PinPositions property in my dto is null. So I hoping that this case should be covered by library: don't try parse null value into GeoJson object.  

Am I missing something? Maybe is better workaround than removing properties from content string before desereliazation? thanks in advance.

**Comment by hakenmt** [comment]
I think this is doable, I'm just not sure it follows the RFC:

A GeoJSON object represents a Geometry, Feature, or collection of Features.

   o  A GeoJSON object is a JSON object.
   o  A GeoJSON object has a member with the name "type".  The value of the member MUST be one of the GeoJSON types.
   o  A GeoJSON object MAY have a "bbox" member, the value of which MUST be a bounding box array (see Section 5).
   o  A GeoJSON object MAY have other members (see Section 6).

I'm open to interpretation and suggestions, do you believe the RFC allows for a GeoJSON object to be null? Or is it trivial?

**Comment by ignasbagdonas** [comment]
It’s only model and business logic. I think it’s not related with RFC. I just want nullable (optional) property of GeoJson. It should have strong structure when content exist, but null is null, I think.
