### ISSUE TITLE
Example 3

### ISSUE THREAD

**Issue by ghost** [bamcis-io/GeoJSON#14]
Example 3 is very straight forward but I need properties as well as coordinates. Do you have and Example like #3 for Features and FeatureCollections?

**Comment by hakenmt** [comment]
I will add an example to the README to cover this.

**Comment by hakenmt** [comment]
Actually, need some additional details on this. If you look at this [test](https://raw.githubusercontent.com/bamcis-io/GeoJSON/master/GeoJSON.Tests/featurecollection.json) data, it's a pretty thorough example of what a `FeatureCollection` might look like in JSON. You'd need to construct multiple features and provide them to the feature collection. What do you want to see in an example?
