### ISSUE TITLE
MultiLineString should support less than two LineStrings?

### ISSUE THREAD

**Issue by chris-e-green** [bamcis-io/GeoJSON#15]
Hi, as far as I understand it, when the RFC says 

`For type "MultiLineString", the "coordinates" member is an array of LineString coordinate arrays`

that would at least include the situation where there is only one linestring present (possibly zero linestrings?). The code, as it stands, rejects a single linestring with an error.

**Comment by hakenmt** [comment]
Ah, I see the error in this, the intent was to check the LineString members of the array to ensure they had 2 coordinates apiece, not to ensure the the coordinates had at least 2 line strings. Genuine bug, I will fix. The RFC is ambiguous, would a null coordinates or empty array be a valid value?

**Comment by chris-e-green** [comment]
I agree - it is rather ambiguous on null coordinates in multilinestrings! With LineStrings, it's explicitly '2 or more positions' and Points are 'a single position'. Under 3.1 (Geometry) it says ` GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects` so that could imply that empty arrays are legitimate unless specifically overridden elsewhere?

**Comment by hakenmt** [comment]
If I update this to allow empty but not null coordinates for MultiLineString, is that acceptable?

**Comment by chris-e-green** [comment]
perfectly acceptable to me! (realistically, I can't think of any circumstances where anyone would want an empty multilinestring anyway)... Thanks for the quick responses!

**Comment by hakenmt** [comment]
But also, given the feature is a "Multi" line string, does it make sense that the feature could contain only 1 (or 0) line string?

**Comment by chris-e-green** [comment]
From a wording point of view yes I'd agree - but from what I'm seeing, one linestring is acceptable/produced by various spatial databases including SQL Server?

**Comment by hakenmt** [comment]
Pushed an updated version to Nuget (2.0.2), I think this should resolve your issue, please let me know if it does not (as well as any other feedback you may have!).

**Comment by chris-e-green** [comment]
Thanks very much Michael!

________________________________

Chris Green
Chief Technical Advisor
Emailchris.green@gruntify.com
Web  www.gruntify.com
