### ISSUE TITLE
Properties are read only.

### ISSUE THREAD

**Issue by Rlcolli4** [bamcis-io/GeoJSON#16]
In my code, I need to take the return value of a geoJson and (depending on logic for my code) remove any holes from the geo json. My code is as follows:
`GeoJson geoJson = this._serializer.deserializeGeoJsonFromString(geojsonGeom);
      FeatureCollection featureCollection = geoJson as FeatureCollection;
      Feature[] features = featureCollection.Features.ToArray();
      for (int i = 0; i < features.Length; i++) {
        Feature f = features[i];
        switch(f.Geometry.Type) {
          ...
          case GeoJsonType.Polygon:
          default:
            Polygon p = (Polygon)f.Geometry;
            p.Coordinates = new LinearRing[] { p.Coordinates.ToArray()[0] };
            break;
        }
      }`
However, when the code tries to compile I get the error `p.Coordinates is a read only property`. Is there a way to set these objects up so I can manipulate them for my code?

**Comment by hakenmt** [comment]
The coordinates are set through the constructor for Polygon. It looks like you're trying to exclude any of the internal linear rings from the coordinates. Is that correct? Is there a reason you wouldn't just create a new Polygon with just that single external linear ring? Trying to understand your end state a little better to see what the best solution/change for this is.

**Comment by Rlcolli4** [comment]
We have a dynamic set of properties that come back on our GeoJson calls in Postgres and the model we send back from the server has those properties with the Coordinates for the object. This data is then used by the client to render the shape and display data. In some instances where we build our shapes there are holes in the polygon, sometimes we want them other times we don't so we manually clear out the holes based on certain conditions.

**Comment by hakenmt** [comment]
Since the library is generally used for serialization, I'm hesitant to make the coordinates settable from outside of the constructor, since I'd need to mimic this behavior in all of the `Geometry` sub classes. Would a method to remove the internal linear rings be sufficient for this use case, or are you setting the coordinates property on other geometry types?

**Comment by Rlcolli4** [comment]
Yeah that would be sufficient. It would probably also simplify our code as well.
