### ISSUE TITLE
Invalid latitude or longitude for Position is accepted instead of an error

### ISSUE THREAD

**Issue by patheems** [bamcis-io/GeoJSON#21]
Environment:

dotnet version : 5.0.100
BAMCIS.GeoJSON version: v 2.1.0

Issue:
When a invalid latitude or longitude is provided in the json the Position object is accepting this, instead of throwing an exception.

Expected:
A check if the latitude/longitude fall within the expected range.

**Comment by GrumpyMan** [comment]
This is fatal when getting GeoJson files that are in other coordinate systems like SWEREF 99. I understand that the RFC states WGS84 but in reality I do stumble on files from different authorities that uses SWEREEF 99 and does not convert it to WGS84.

Although this check is correct it would be great if there at least could be some option to ignore this check.

**Comment by hakenmt** [comment]
@GrumpyMan does this work for your needs? https://github.com/bamcis-io/GeoJSON/pull/25

**Comment by GrumpyMan** [comment]
Sorry, did not see your answer before now. Will check this weekend.

**Comment by GrumpyMan** [comment]
This works for my use case. Thanks a lot and sorry for the late reply.
