### ISSUE TITLE
Question regarding PolygonConverter

### ISSUE THREAD

**Issue by patheems** [bamcis-io/GeoJSON#29]
Hi,

I've got a question regarding the PolygonConverter.

What is the reason you check if the typeToConvert == MultiPolygon instead of Polygon in the PolygonConverter? https://github.com/bamcis-io/GeoJSON/blob/main/GeoJSON/Serde/PolygonConverter.cs

**Comment by hakenmt** [comment]
That's a good question, though it doesn't seem to impact the actual serde process. Let me look at it, may have been a bad intellisense substitution.
