### ISSUE TITLE
Not able to install on .NET 4.0

### ISSUE THREAD

**Issue by MV88** [bamcis-io/GeoJSON#3]
Hello, I hope you are good.
I'm having trouble installing your library in our project (using .NET 4.0)

this is what nuGet reports:

> Installing 'GeoJSON 1.1.0'. Successfully installed 'GeoJSON 1.1.0'. Adding 'GeoJSON 1.1.0' to CMapServiceLibrary. Uninstalling 'GeoJSON 1.1.0'. Successfully uninstalled 'GeoJSON 1.1.0'. Install failed. Rolling back... Could not install package 'GeoJSON 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

let me know if you need more details,
Cheers Matteo

**Comment by hakenmt** [comment]
This project targets netstandard1.6, which requires a minimum of .NET Framework 4.6.1. I don't believe anything in .NET Core is compatible with .NET Framework below 4.5. You can review this [link](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) to see the interoperability matrix,. Let me know if that's the problem.
