### ISSUE TITLE
[Geo]JSON is case-sensitive, must use `type` instead of `Type`, etc.

### ISSUE THREAD

**Issue by mormegil-cz** [bamcis-io/GeoJSON#8]
GeoJSON produced by the library is invalid, as it uses wrongly-capitalized field names, e.g. `"Type":"FeatureCollection"` instead of the correct `"type":"FeatureCollection"`.

As JSON (and GeoJSON) is case-sensitive, this is an important difference, meaning the produced GeoJSON does not work elsewhere.

**Comment by hakenmt** [comment]
Yes, you are correct. When I developed this I was using a serde that wasn't case sensitive, but it is an important thing to fix.
